-- V1: Create users table for authentication
CREATE TABLE users (
    user_id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index for faster lookups
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);

-- Insert demo users (password is 'password123' hashed with bcrypt cost=10)
-- Hash generated by Java Spring Security BCryptPasswordEncoder
INSERT INTO users (username, email, password_hash) VALUES
    ('alice', 'alice@example.com', '$2a$10$qec4Yv7E8SELBzIInFacROUk3.k82Zag3/c2hLbSuCCR85qneH9h2'),
    ('bob', 'bob@example.com', '$2a$10$qec4Yv7E8SELBzIInFacROUk3.k82Zag3/c2hLbSuCCR85qneH9h2'),
    ('charlie', 'charlie@example.com', '$2a$10$qec4Yv7E8SELBzIInFacROUk3.k82Zag3/c2hLbSuCCR85qneH9h2');
