apiVersion: v1
kind: Secret
metadata:
  name: litebank-secrets
  labels:
    {{- include "litebank.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.secrets.dbPassword | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  jwt-expiration: {{ .Values.secrets.jwtExpiration | quote }}
